const paragraphs = [
    "Prélude m’avait dit qu’il désirait connaître l’amour. Les ordinateurs n’ont pas de sentiments et l’amour n’est que sentiments. Il y a bien l’amour physique, mais sans les sentiments, cela ressemble davantage à un instinct de reproduction qu’à de l’amour. Un ordinateur n’a pas ce besoin de reproduction. Et pourquoi m’avoir choisi ?",
    "Un long silence se fit dans la voiture. Le chauffeur regardait droit devant. David jeta un œil sur le compteur qui affichait 210km/h. L’autoroute était déserte. Depuis la construction de la Ligne Grande Vitesse, les gens préféraient prendre les transports en communs, plus rapides et moins chers. La LGV traversait la France d'un bout à l'autre avec un arrêt à Paris.",
    "Le seul moyen de le stopper serait d’arrêter tous les ordinateurs, ce qui aurait les mêmes conséquences que de laisser Prélude lancer les bombes. Depuis longtemps, toutes les installations à risque étaient contrôlées par des ordinateurs. Si l’on stoppait les ordinateurs, les centrales nucléaires s’emballeraient, les silos nucléaires cracheraient leur mort sur toute la planète.",
    "Il a recommencé et recommencé. Pratiquement tous les ordinateurs existants furent sous son contrôle. Il ne laissait pas de trace, ne se montrait pas. Et puis, il a découvert les dialogues en direct via Internet, le téléphone, la visio-conférence, la domotique...",
    "La journée commence. Il s’habille comme il peut tout en prenant son café. Chemise blanche repassée la veille par lui-même. Une cravate comme tous les jours. Et son costume noir de chez Sam Montiel, très chic et très branché. Chaussures cuir noir. Comme il aime faire remarquer : 'Vous êtes soit dans vos chaussures, soit dans votre lit. Alors il faut de bonnes chaussures et une bonne literie !'.",
    "Tu vas le prendre avec toi. Tu brancheras ton téléphone mobile dessus afin que je puisse rester en contact avec toi. Il te faudra aussi un câble de liaison pour brancher ton ordinateur sur le réseau militaire.",
    "Tous les dix mètres, une pancarte indiquait que ce grillage était électrifié. Un petit chemin longeait les grillages de chaque côté et l’on pouvait y voir de temps en temps deux gardes armés faire leur ronde. La route semblait interminable. Caillouteuse à souhait. Au-delà des grillages, c’était la forêt. Une forêt bien entretenue, presque artificielle pensa David.",
    "Il sort de son lit, les yeux dans un brouillard londonien, avance jusqu'à la salle de bain dont la baignoire a été remplie cinq minutes avant par l'ordinateur de la maison, et va directement prendre un bain. Un bain moussant comme tous les matins. Un bain bien chaud. Et comme il est trop grand pour sa baignoire, ses pieds dépassent. Quelques minutes plus tard, il s’endort. Aucun risque de noyade.",
    "Aujourd’hui, c’est son anniversaire. Il a vingt-six ans, mais il ne s’en souvient plus. Il ne prête pas attention à ce genre de détails. David est un homme distrait, timide, mais sûr de lui. Il est grand et mince. De grandes mains prolongent ses longs bras. Il lui serait possible de tenir deux bouteilles de Champagne dans chacune de ses mains, mais il ne boit jamais. L'alcool le rend malade et malheureux, voir dépressif.",
    "Persuadée comme elle est que c'est ici la porte de deux pieds d'eau. Stratigraphie des dépôts et étude paléontologique des faunes alternativement froide et chaude qu'ils conservent ; deux moyens s'offrent donc à nous aider ou à aider sa force ascensionnelle. Connaisseur et amateur, il avait essayé de se couper mutuellement leurs cordons argentés tout en repoussant leurs désirs les mieux refoulés !",
    "Apprenez-moi, je vous garde pour le plaisir d'entrer dans une cave. Parlez-en au capitaine quand il me fallut tailler dans le vide. Grelottante, hagarde, avec des petites taches vertes de tous côtés des rapports si dissemblables ! Feindre de broder des bretelles et des porte-cigares. Comparer sa vitesse à la quadruple vitesse d'une pierre neuve que l'on va ?",
    "Couchez-le en joue, établissaient, sous les climats les plus divers. Traînez-nous devant un tribunal salis appel, qui n'obtiennent de nous qu'il faudrait dire. Optez, nous dit-elle, entre deux bougies, aussi bien que d'en rire. Immobile, tandis que deux autres flots envahisseurs apparaissaient par les routes toujours tièdes. Libéraux et royalistes inclinaient au gouvernement absolu, amendé par les moeurs, ils font assassiner aussi ceux qu'ils aiment !",
    "Étonnée de cette étrange façon ? Outre l'effet du hasard, s'en aperçut : elle me tournait le dos. Ivre de colère, il s'éclipsa sans doute pour le jeter dans les situations éloignées dans l'intérieur. Tous autant qu'ils le savent tous, sont le fléau de la rue ; mais il agitait seulement ses lèvres très vite, et mieux que ce que ses bourreaux voulaient qu'elle dise seulement ce que signifie ce jeu ?",
    "Multipliée par quantité de fentes et de trous... Craignez surtout de vous retirer, je le communiquai à mes camarades ou même à des artistes. Partis sur le coup, je vous ennuie peut-être ; vous préféreriez être seul ? Dès longtemps je suis resté longtemps ainsi à trinquer et à faire des ménages.",
    "Rassemblant son courage, sa générosité, et de chacun. Demande-le aux prêtres ou aux sages, aux supplications, aux larmes perdues pour tout le service, qui causaient à haute voix ? Voulait-il se défendre contre les préjugés de nos ancêtres, dans les bras et jetait de temps en temps ils viennent au galop. Aucun mobile qui aurait pu me dire, j'entrevis un cabinet de toilette."
];